fastlane_version '2.125.0'
before_all do
  # ensure_git_branch
  # ensure_git_status_clean
  # git_pull
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= '12345678'
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      match(app_identifier: 'com.mpigm.piyangosepeti', type: 'appstore', readonly: true)
    end

  desc 'Build the iOS application.'
    private_lane :build do
      # certificates
      # increment_build_number(xcodeproj: './ios/MpiPiyangoSepetiMobil.xcodeproj')
      gym(scheme: 'MpiPiyangoSepetiMobil', workspace: './ios/MpiPiyangoSepetiMobil.xcworkspace')
    end

  desc 'Ship to Testflight.'
    lane :beta do
      certificates
      build
      upload_to_testflight(
        username: "murat@aritaturk.com"
      )

    end

end

platform :android do
  desc 'Build the Android application.'
    private_lane :build do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
    end

  desc 'Ship to Playstore Beta.'
    lane :beta do
      build
      supply(track: 'beta', track_promote_to: 'beta')
      # git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
      # push_to_git_remote
    end


  desc "android deploy"
    lane :prodDeploy do
      gradle(task: 'clean' , project_dir: 'android/' )
      gradle(task: 'assemble', flavor: 'Ps', build_type: 'Release', project_dir: 'android/')
    end

  desc "firebase deploy"
    lane :devDeploy do
      gradle(task: 'assemble', flavor: 'Ps', build_type: 'Release', project_dir: 'android/')

        firebase_app_distribution(
            app: "INSERT_YOUR_APP_ID_HERE",
            release_notes: "Test",
            firebase_cli_token: "INSERT_YOUR_TOKEN_HERE",
            groups: "aritaturk"
        )

    end
     desc "firebase cyprus deploy"
        lane :prodCyprusDeploy do
          gradle(task: 'assemble', flavor: 'Cyprus', build_type: 'Release',  project_dir: 'android/')

    end
     desc "firebase cyprus deploy dev"
        lane :devCyprusDeploy do
            gradle(task: 'assemble', flavor: 'Cyprus', build_type: 'Release',  project_dir: 'android/')
            firebase_app_distribution(
                 app: "INSERT_YOUR_APP_ID_HERE",
                release_notes: "Test",
                firebase_cli_token: "INSERT_YOUR_TOKEN_HERE",
                groups: "aritaturk"
            )
     end
end
